// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXuylPkdYqdXIgUyk75JQomhlTTuzo4EE',
    appId: '1:29493572137:web:31566813f8aa4719596238',
    messagingSenderId: '29493572137',
    projectId: 'atlasfitness-806b2',
    authDomain: 'atlasfitness-806b2.firebaseapp.com',
    storageBucket: 'atlasfitness-806b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX4zi7Tep5GFyxV2YH2yiFlGhee7xSFUU',
    appId: '1:29493572137:android:6932ff7e95dd2ad7596238',
    messagingSenderId: '29493572137',
    projectId: 'atlasfitness-806b2',
    storageBucket: 'atlasfitness-806b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsW2Bh310wUb0nj-WBnt8D2oqTh_OCrv8',
    appId: '1:29493572137:ios:c0b1a39b931ed7f8596238',
    messagingSenderId: '29493572137',
    projectId: 'atlasfitness-806b2',
    storageBucket: 'atlasfitness-806b2.appspot.com',
    iosBundleId: 'com.example.atlasFitness',
  );
}
