import 'dart:math';

class DailyTipBase {
  static final  List<String> _dailyTips = [
    "Always remember to stay hydrated ❤",
    "Eat a balanced diet rich in fruits and vegetables 🌽🍇.",
    "Exercise regularly to maintain a healthy body and mind 🏋️‍♂️.",
    "Include more whole grains in your meals 🍞.",
    "Choose lean proteins like fish and chicken 🐟.",
    "Limit your intake of added sugars 🍭.",
    "Get enough sleep to recharge your body 💤.",
    "Practice portion control to avoid overeating 🍽️.",
    "Incorporate more plant-based foods into your diet 🌱.",
    "Drink green tea for its antioxidants 🍵.",
    "Snack on nuts for a healthy dose of fats and protein 🌰.",
    "Avoid trans fats found in processed foods 🚫.",
    "Take a walk after meals to aid digestion 🚶‍♀️.",
    "Eat slowly to allow your body to recognize fullness 🕒.",
    "Limit your intake of sodium to maintain healthy blood pressure 🌡️.",
    "Include fiber-rich foods in your diet for better digestion 🌾.",
    "Opt for homemade meals over fast food 🍲.",
    "Include probiotics in your diet for gut health 🦠.",
    "Stay active throughout the day, even if it's just light stretching 🤸‍♀️.",
    "Avoid drinking calories; choose water over sugary drinks 💧.",
    "Add more color to your plate with a variety of fruits and veggies 🌈.",
    "Practice mindful eating; focus on your food without distractions 🧘‍♂️.",
    "Replace refined grains with whole grains 🍚.",
    "Stay consistent with your exercise routine 💪.",
    "Avoid eating late at night 🕙.",
    "Manage stress with relaxation techniques like deep breathing 🧘‍♀️.",
    "Make time for physical activity every day, even if it's just 30 minutes 🕑.",
    "Limit alcohol consumption 🍷.",
    "Try new recipes to keep your meals interesting 🍜.",
    "Keep healthy snacks on hand to avoid junk food 🥗.",
    "Stay connected with friends and family for emotional well-being 👨‍👩‍👧.",
    "Get outside and enjoy nature 🌳.",
    "Set realistic goals for your health and fitness journey 🥅.",
    "Eat more omega-3 fatty acids, found in fish and flaxseeds 🐟.",
    "Drink a glass of water before meals to prevent overeating 💧.",
    "Keep a food journal to track your eating habits 📔.",
    "Add spices like turmeric and ginger to your meals for added health benefits 🌶️.",
    "Practice gratitude to improve your mental health 🙏.",
    "Incorporate strength training into your fitness routine 🏋️.",
    "Don't skip breakfast; start your day with a healthy meal 🍳.",
    "Limit your screen time before bed to improve sleep quality 🛌.",
    "Eat a variety of foods to ensure you get all the necessary nutrients 🌍.",
    "Take the stairs instead of the elevator for extra physical activity 🏃‍♂️.",
    "Include dark leafy greens in your diet for their vitamins and minerals 🥬.",
    "Practice good hygiene, like washing hands regularly 🧼.",
    "Avoid ultra-processed foods that are high in unhealthy fats and sugars 🥡.",
    "Take breaks during work to stretch and move around 🧍‍♀️.",
    "Listen to your body; rest when you need to 🛋️.",
    "Focus on positive thoughts to boost your mental health 😊.",
    "Add a salad to your meals for extra nutrients 🥗.",
    "Eat foods rich in iron, like spinach and legumes 🥬.",
    "Start your day with a positive affirmation 🌞.",
    "Take a moment to breathe deeply and relax 🧘‍♀️.",
    "Eat more beans and legumes for plant-based protein 🥙.",
    "Include healthy fats like avocados and olive oil in your diet 🥑.",
    "Drink herbal teas for their calming effects ☕.",
    "Avoid smoking and exposure to secondhand smoke 🚭.",
    "Cook with fresh ingredients rather than relying on packaged foods 🍲.",
    "Spend time doing activities you enjoy to boost your mood 🎨.",
    "Eat fermented foods like yogurt and kimchi for gut health 🥛.",
    "Use smaller plates to help control portion sizes 🍽️.",
    "Choose low-fat or fat-free dairy products 🧀.",
    "Get regular check-ups to monitor your health 🩺.",
    "Incorporate more fresh herbs into your cooking for added flavor and nutrients 🌿.",
    "Start your meals with a serving of vegetables to increase your fiber intake 🥦.",
    "Include berries in your diet for their antioxidant properties 🍓.",
    "Take time to chew your food thoroughly to aid digestion 🦷.",
    "Avoid eating in front of the TV or computer to prevent mindless eating 📺.",
    "Get moving during TV commercials with short exercises like jumping jacks 📺🏃‍♀️.",
    "Incorporate meditation into your daily routine for mental clarity 🧘‍♂️.",
    "Use a standing desk or take standing breaks if you sit for long periods 🖥️.",
    "Eat foods rich in Vitamin C, like oranges and bell peppers 🍊.",
    "Make sure to warm up before exercising to prevent injury 🤸‍♂️.",
    "Avoid eating out of large packages to better control portions 📦.",
    "Take a moment to relax and unwind before bed to improve sleep quality 🌙.",
    "Add more protein to your breakfast to keep you fuller longer 🍳.",
    "Use natural sweeteners like honey or maple syrup instead of refined sugar 🍯.",
    "Swap out sugary desserts for fresh fruit 🍇.",
    "Practice deep breathing exercises to reduce stress 🧘‍♀️.",
    "Eat more seafood for its heart-healthy omega-3 fatty acids 🐠.",
    "Incorporate more movement into your day by parking farther away 🅿️.",
    "Try batch cooking to ensure you have healthy meals ready throughout the week 🍱.",
    "Use herbs and spices instead of salt to flavor your meals 🌿.",
    "Practice positive self-talk to maintain motivation and well-being 🗣️.",
    "Eat more seeds, like chia and flaxseeds, for added fiber and omega-3s 🌰.",
    "Take a break from caffeine and drink more water instead ☕🚫.",
    "Make sure to include a source of calcium in your diet, like dairy or leafy greens 🥛.",
    "Avoid skipping meals to keep your energy levels stable throughout the day 🍽️.",
    "Include colorful peppers in your meals for a boost of vitamins A and C 🌶️.",
    "Stretch after your workouts to improve flexibility and reduce muscle soreness 🤸‍♀️.",
    "Reduce your intake of red meat and opt for plant-based proteins 🍔🚫.",
    "Make time for hobbies that relax you, like reading or gardening 📚.",
    "Try to maintain a consistent sleep schedule, even on weekends ⏰.",
    "Make water your go-to beverage to stay hydrated 💦.",
    "Get a friend to join you in your fitness routine for added motivation 🤝.",
    "Incorporate balance exercises into your workouts to improve stability ⚖️.",
    "Take care of your mental health by talking to a friend or counselor if needed 🗨️.",
    "Limit your intake of fried foods to reduce unhealthy fats 🍟🚫.",
    "Start your day with a glass of lemon water for a refreshing boost 🍋.",
    "Take the time to enjoy your meals and savor the flavors 🍽️.",
    "Include Vitamin D-rich foods like eggs and mushrooms in your diet 🍳🍄.",
    "Practice yoga or pilates to improve your flexibility and strength 🧘‍♂️.",
    "Keep your kitchen stocked with healthy staples like whole grains and legumes 🛒.",
    "Remember that consistency is key to achieving your health goals 🔑.",
    "Eat dark chocolate in moderation for its antioxidant benefits 🍫.",
    "Get creative with your salads by adding a variety of colorful vegetables 🥗.",
    "Limit processed meats like sausages and bacon to reduce your sodium intake 🌭🚫.",
    "Take time to laugh and enjoy life to reduce stress and boost your mood 😂.",
    "Include more citrus fruits in your diet for their immune-boosting Vitamin C 🍋.",
    "Avoid drinking energy drinks, as they can be high in sugar and caffeine 🥤🚫.",
    "Take a break from your phone and enjoy some screen-free time 📵.",
    "Eat more mushrooms for their immune-boosting properties 🍄.",
    "Make sure to get some sunlight each day for natural Vitamin D 🌞.",
    "Include garlic in your meals for its heart-healthy benefits 🧄.",
    "Take time to declutter your space to create a calming environment 🧹.",
    "Make sure to balance your meals with protein, carbs, and healthy fats ⚖️.",
    "Use a reusable water bottle to stay hydrated throughout the day 🥤.",
    "Eat more cauliflower for its versatility and nutrient content 🥦.",
    "Avoid eating when you're bored; find an activity to keep you occupied 🎲.",
    "Incorporate more nuts like almonds and walnuts into your snacks 🌰.",
    "Swap out white rice for quinoa or brown rice for added fiber 🍚.",
    "Eat more fiber-rich foods like oatmeal and lentils for better digestion 🌾.",
    "Try to avoid multitasking while eating to fully enjoy your food 🧠🍽️.",
    "Incorporate more colorful fruits like berries and melons into your diet 🍉.",
    "Use olive oil instead of butter for cooking to reduce saturated fat intake 🍳.",
    "Make sure to get regular eye check-ups if you spend a lot of time on screens 👀.",
    "Try new physical activities like dancing or swimming for fun exercise 💃🏊‍♂️.",
    "Include lean beef in your diet for a good source of iron and protein 🥩."
    ];

    static String getRandomTip() {
    final random = Random();
    return _dailyTips[random.nextInt(_dailyTips.length)];
  }

}